services:
  - type: web
    name: sistema-cadastro-ean
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src 'main:app' --log-file -
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-cadastro-ean-db
          property: connectionString

databases:
  - name: sistema-cadastro-ean-db
    plan: free
